name: Lint
on:
  push:
    # paths:
    #   - 'src/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Lint
        working-directory: ./src
        run: golangci-lint run