name: Lint
on:
  push:
    paths:
      - 'src/**'

jobs:
  lint-job:
    name: Lint-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./src
