name: Lint
on:
  pull_request:
      branches:
          - main
      paths:
      - '**/*.go'


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
      - name: Test
        uses: n8maninger/action-golang-test@v1
        with:
          args: "-race;-failfast;-tags=testing debug netgo"

          name: Test

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        uses: n8maninger/action-golang-test@v1
        with:
          args: "-race;-failfast;-tags=testing debug netgo"
