name: Test
on:
    pull_request:
        branches:
            - main
        paths:
        - '**/*.go'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: stable

      - name: Test
        uses: n8maninger/action-golang-test@v1
        with:
          args: "-race;-failfast;-tags=testing debug netgo"
